# Generated by Django 5.0 on 2024-01-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_post_title", models.CharField(max_length=2000)),
                ("blog_post_date", models.CharField(max_length=2000)),
                ("blog_post_image", models.ImageField(upload_to="")),
                ("blog_post_text", models.CharField(max_length=100000)),
                ("blog_card_title", models.CharField(max_length=2000)),
                ("blog_card_caption", models.CharField(max_length=2000)),
                ("blog_card_image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Ghat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ghat", models.CharField(max_length=200)),
            ],
        ),
    ]
