# Generated by Django 5.0 on 2024-01-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="blog_card_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="blog_post_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
